from fpdf import FPDF
import re
import tempfile
import os


class ArticlePDF(FPDF):

    def header(self):
        self.set_font("DejaVu", "B", 10)
        self.set_text_color(255, 75, 75)
        self.cell(0, 10, "YouTube to Insightful Article", align="L")

        self.set_font("DejaVu", "", 10)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by AI", align="R")
        self.ln()

        self.set_draw_color(220, 220, 220)
        self.line(10, 20, 200, 20)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def clean_text(text: str) -> str:
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'`(.*?)`', r'\1', text)
    text = re.sub(r'<[^>]+>', '', text)
    return text.strip()


def generate_pdf(article: str, video_title: str = "YouTube Video") -> str:
    pdf = ArticlePDF()

    # ✅ Safe font path (VERY IMPORTANT)
    font_path = os.path.join(os.path.dirname(__file__), "DejaVuSans.ttf")

    pdf.add_font("DejaVu", "", font_path, uni=True)
    pdf.add_font("DejaVu", "B", font_path, uni=True)

    pdf.set_font("DejaVu", "", 10)

    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(15, 25, 15)

    pdf.add_page()   # ✅ AFTER font setup

    # ✅ Video Title
    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 10, video_title)
    pdf.ln(5)

    lines = article.strip().split('\n')

    for line in lines:
        raw = line.strip()

        if not raw:
            pdf.ln(3)
            continue

        # 🔹 H1
        if raw.startswith('# '):
            pdf.set_font("DejaVu", "B", 18)
            pdf.set_text_color(255, 75, 75)
            pdf.multi_cell(0, 10, clean_text(raw[2:]))
            pdf.ln(4)

        # 🔹 H2
        elif raw.startswith('## '):
            pdf.set_font("DejaVu", "B", 13)
            pdf.set_text_color(50, 50, 150)
            pdf.multi_cell(0, 8, clean_text(raw[3:]))
            pdf.ln(2)

        # 🔹 H3
        elif raw.startswith('### '):
            pdf.set_font("DejaVu", "B", 11)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(0, 7, clean_text(raw[4:]))
            pdf.ln(1)

        # 🔹 Bullet points
        elif raw.startswith('- ') or raw.startswith('* '):
            pdf.set_font("DejaVu", "", 10)
            pdf.set_text_color(40, 40, 40)
            pdf.set_x(20)
            pdf.cell(5, 6, "-")
            pdf.set_x(26)
            pdf.multi_cell(0, 6, clean_text(raw[2:]))
            pdf.ln(1)

        # 🔹 Numbered list
        elif re.match(r'^\d+\.', raw):
            pdf.set_font("DejaVu", "", 10)
            pdf.multi_cell(0, 6, clean_text(raw))
            pdf.ln(1)

        # 🔹 Paragraph
        else:
            para = clean_text(raw)
            if para:
                pdf.set_font("DejaVu", "", 10)
                pdf.set_text_color(40, 40, 40)
                pdf.multi_cell(0, 7, para)
                pdf.ln(2)

    # ✅ Save PDF
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    pdf.output(tmp.name)

    return tmp.name